"""Move every style="..." attribute into a generated utility class.

This is what lets the CSP drop 'unsafe-inline' from style-src.

Inline styles outrank any class selector, so the generated rules carry
!important to preserve exactly the precedence they had before. They are emitted
in a clearly-marked block at the end of style.css and are keyed by a hash of the
declaration, so re-running this script is idempotent.
"""
import glob
import hashlib
import os
import re

ROOT = r"c:\Users\User\OneDrive\Documents\Programming\HandD1photos"
os.chdir(ROOT)

MARK_START = "/* === BEGIN generated utilities (extracted from inline style attributes) === */"
MARK_END = "/* === END generated utilities === */"


def class_for(decl):
    return 'u-' + hashlib.sha1(decl.encode('utf-8')).hexdigest()[:7]


def add_important(decl):
    """Match the precedence an inline style attribute had."""
    out = []
    for part in decl.split(';'):
        part = part.strip()
        if not part:
            continue
        out.append(part if part.endswith('!important') else part + ' !important')
    return '; '.join(out) + ';'


# ---- 1. collect every distinct declaration -------------------------------
decls = {}
for f in sorted(glob.glob('*.html')):
    s = open(f, encoding='utf-8').read()
    for m in re.findall(r'\sstyle="([^"]*)"', s):
        d = m.strip()
        if d:
            decls[d] = class_for(d)

# ---- 2. rewrite the markup ------------------------------------------------
changed = 0
for f in sorted(glob.glob('*.html')):
    s = open(f, encoding='utf-8').read()
    orig = s

    def swap(m):
        decl = m.group(2).strip()
        if not decl:
            return ''
        return ' data-hdstyle="' + decls[decl] + '"'

    s = re.sub(r'\s(style)="([^"]*)"', swap, s)

    # Fold the placeholder into the element's existing class attribute, or add one.
    def fold(m):
        tag = m.group(0)
        holders = re.findall(r'\sdata-hdstyle="([^"]+)"', tag)
        if not holders:
            return tag
        tag = re.sub(r'\sdata-hdstyle="[^"]+"', '', tag)
        add = ' '.join(holders)
        if re.search(r'\sclass="', tag):
            tag = re.sub(r'(\sclass=")([^"]*)(")',
                         lambda c: c.group(1) + (c.group(2) + ' ' + add).strip() + c.group(3),
                         tag, count=1)
        else:
            tag = re.sub(r'^<([a-zA-Z0-9]+)', r'<\1 class="' + add + '"', tag, count=1)
        return tag

    s = re.sub(r'<[a-zA-Z][^>]*>', fold, s)

    if s != orig:
        open(f, 'w', encoding='utf-8', newline='').write(s)
        changed += 1

# ---- 3. emit the stylesheet block ----------------------------------------
css = open('style.css', encoding='utf-8').read()
if MARK_START in css:
    css = css[:css.index(MARK_START)].rstrip() + '\n'

lines = [
    '',
    MARK_START,
    '/* Machine-generated by scripts/extract_styles.py — do not hand-edit.',
    '   These replace the style="..." attributes the pages used to carry, which is',
    '   what allows style-src to drop \'unsafe-inline\'. !important reproduces the',
    '   precedence an inline attribute had. Folding these into the semantic',
    '   component classes above is worthwhile cleanup, but not a security issue. */',
]
for decl, cls in sorted(decls.items(), key=lambda kv: kv[1]):
    lines.append('.%s{ %s }' % (cls, add_important(decl)))
lines.append(MARK_END)

open('style.css', 'w', encoding='utf-8', newline='').write(css + '\n'.join(lines) + '\n')

print(f'{len(decls)} unique declarations -> utility classes')
print(f'{changed} HTML files rewritten')
remaining = sum(len(re.findall(r'\sstyle="', open(f, encoding='utf-8').read()))
                for f in glob.glob('*.html'))
print(f'inline style attributes remaining: {remaining}')
